backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "shirt" # Used in routes, e.g., /admin/collections/blog
    label: "Shirt" # Used in the UI
    folder: "src/shirts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter.
    # Remove any that aren't needed for posts
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Size", name: "size", widget: "select", options: ["Small", "Medium", "Large"]}
      - {label: "Small", name: "small", widget: "number"}
      - {label: "Medium", name: "medium", widget: "number"}
      - {label: "Large", name: "large", widget: "number"}
      - {label: "XLarge", name: "xlarge", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Price", widget: "number", name: "price"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Second Image", name: "thumbnail2", widget: "image"}
      - {label: "Third Image", name: "thumbnail3", widget: "image"}
      - {label: "Fourth Image", name: "thumbnail4", widget: "image"}
